package org.team4u.actiondock.browser.plugin;

final class BrowserGatewayActions implements BrowserActionRegistrar {
    private final BrowserGatewayService service;

    BrowserGatewayActions(BrowserGatewayService service) {
        this.service = service;
    }

    @Override
    public void registerTo(BrowserActionRegistry registry) {
        registry.register("sessionCreate", service::createSession)
                .register("sessionClose", service::closeSession)
                .register("sessionInfo", service::sessionInfo)
                .register("sessionList", (context, args) -> service.sessionList(context))
                .register("observe", service::observe)
                .register("capabilities", (context, args) -> BrowserActionSpecs.capabilities())
                .register("goto", service::gotoPage)
                .register("reload", service::reloadPage)
                .register("goBack", service::goBack)
                .register("goForward", service::goForward)
                .register("click", service::click)
                .register("doubleClick", service::doubleClick)
                .register("hover", service::hover)
                .register("fill", service::fill)
                .register("typeText", service::typeText)
                .register("clear", service::clear)
                .register("press", service::press)
                .register("check", service::check)
                .register("uncheck", service::uncheck)
                .register("setChecked", service::setChecked)
                .register("selectOption", service::selectOption)
                .register("setInputFiles", service::setInputFiles)
                .register("focus", service::focus)
                .register("blur", service::blur)
                .register("scrollIntoView", service::scrollIntoView)
                .register("selectText", service::selectText)
                .register("tap", service::tap)
                .register("dispatchEvent", service::dispatchEvent)
                .register("dragTo", service::dragTo)
                .register("setContent", service::setContent)
                .register("addScriptTag", service::addScriptTag)
                .register("addStyleTag", service::addStyleTag)
                .register("screenshot", service::screenshotPage)
                .register("locatorScreenshot", service::screenshotLocator)
                .register("pdf", service::savePdf)
                .register("dialogAccept", service::dialogAccept)
                .register("dialogDismiss", service::dialogDismiss)
                .register("downloadSaveAs", service::downloadSaveAs)
                .register("evaluate", service::evaluate)
                .register("waitForLoadState", service::waitForLoadState)
                .register("waitForSelector", service::waitForSelector)
                .register("waitForUrl", service::waitForUrl)
                .register("waitForFunction", service::waitForFunction)
                .register("waitForRequest", service::waitForRequest)
                .register("waitForResponse", service::waitForResponse)
                .register("waitForConsole", service::waitForConsole)
                .register("waitForPopup", service::waitForPopup)
                .register("waitForDownload", service::waitForDownload)
                .register("waitForTimeout", service::waitForTimeout)
                .register("pageList", service::pageList)
                .register("pageNew", service::pageNew)
                .register("pageSwitch", service::pageSwitch)
                .register("pageClose", service::pageClose)
                .register("pageBringToFront", service::pageBringToFront)
                .register("events", service::events)
                .register("cookiesGet", service::cookiesGet)
                .register("cookiesSet", service::cookiesSet)
                .register("cookiesClear", service::cookiesClear)
                .register("storageState", service::storageState)
                .register("permissionsGrant", service::permissionsGrant)
                .register("permissionsClear", service::permissionsClear)
                .register("networkRoute", service::networkRoute)
                .register("networkUnroute", service::networkUnroute)
                .register("networkSetOffline", service::networkSetOffline)
                .register("networkSetExtraHTTPHeaders", service::networkSetExtraHTTPHeaders)
                .register("httpRequest", service::httpRequest)
                .register("mouse", service::mouse)
                .register("keyboard", service::keyboard)
                .register("touchscreenTap", service::touchscreenTap)
                .register("viewportSet", service::viewportSet)
                .register("geolocationSet", service::geolocationSet)
                .register("emulateMedia", service::emulateMedia)
                .register("advancedAction", service::act);
    }
}
