package org.team4u.actiondock.project.knowledge.plugin.executor;

import org.team4u.actiondock.plugin.api.ScriptPluginContext;
import org.team4u.actiondock.project.knowledge.plugin.domain.AtomicTask;
import org.team4u.actiondock.project.knowledge.plugin.domain.MaintenanceRequest;
import org.team4u.actiondock.project.knowledge.plugin.domain.RepositoryFacts;
import org.team4u.actiondock.project.knowledge.plugin.domain.TaskResult;

import java.util.LinkedHashMap;
import java.util.Map;

public class LocalAtomicTaskExecutor implements AtomicTaskExecutor {
    @Override
    public TaskResult execute(ScriptPluginContext context, MaintenanceRequest request, RepositoryFacts facts, AtomicTask task, String template) {
        Map<String, Object> parsed = new LinkedHashMap<>();
        parsed.put("title", task.title());
        parsed.put("taskType", task.taskType());
        parsed.put("evidence", task.evidence());
        parsed.put("summary", "Generated by deterministic fallback because AI output was unavailable or not required.");
        parsed.put("templateName", task.templateName());
        return new TaskResult(task.id(), task.taskType(), "done", null, parsed, null, task.outputPath());
    }
}
