import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { computeManifestDigest } from "./digest";
import { loadManifest } from "./manifest";
import type { ActionDockManifest } from "./types";

export const GENERATED_TYPES_REL_PATH = join(".actiondock", "generated", "actions.d.ts");
export const GENERATED_TYPES_OUTDATED_CODE = "GENERATED_TYPES_OUTDATED";

/**
 * 将 JSON Schema 递归转换为 TypeScript 类型声明字符串。
 */
export function jsonSchemaToTypeScript(schema: any, indent = 0): string {
  if (!schema || typeof schema !== "object" || Object.keys(schema).length === 0) {
    return "unknown";
  }
  if (schema.enum && Array.isArray(schema.enum)) {
    return schema.enum.map((v: any) => JSON.stringify(v)).join(" | ");
  }
  if (schema.anyOf && Array.isArray(schema.anyOf)) {
    return `(${schema.anyOf.map((s: any) => jsonSchemaToTypeScript(s, indent)).join(" | ")})`;
  }
  if (schema.oneOf && Array.isArray(schema.oneOf)) {
    return `(${schema.oneOf.map((s: any) => jsonSchemaToTypeScript(s, indent)).join(" | ")})`;
  }
  if (schema.allOf && Array.isArray(schema.allOf)) {
    return `(${schema.allOf.map((s: any) => jsonSchemaToTypeScript(s, indent)).join(" & ")})`;
  }

  const type = schema.type;
  if (type === "string") return "string";
  if (type === "number" || type === "integer") return "number";
  if (type === "boolean") return "boolean";
  if (type === "null") return "null";
  if (type === "array") {
    const items = schema.items ? jsonSchemaToTypeScript(schema.items, indent) : "unknown";
    return `Array<${items}>`;
  }
  if (type === "object" || schema.properties) {
    const props = schema.properties || {};
    const required = new Set(Array.isArray(schema.required) ? schema.required : []);
    const propKeys = Object.keys(props);
    if (propKeys.length === 0) {
      return "Record<string, unknown>";
    }
    const spaces = " ".repeat(indent + 2);
    const closeSpaces = " ".repeat(indent);
    const lines = propKeys.map((k) => {
      const isReq = required.has(k);
      const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
      const opt = isReq ? "" : "?";
      const doc = props[k]?.description
        ? `${spaces}/** ${props[k].description.replace(/\*\//g, "* /")} */\n`
        : "";
      return `${doc}${spaces}${safeKey}${opt}: ${jsonSchemaToTypeScript(props[k], indent + 2)};`;
    });
    return `{\n${lines.join("\n")}\n${closeSpaces}}`;
  }

  return "unknown";
}

/**
 * 将 Action 标识符转换为合法的 TypeScript 标识符（PascalCase）。
 */
function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase())
    .replace(/^[a-z]/, (chr) => chr.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, "");
}

/**
 * 根据项目清单 Schema 生成类型声明文件内容，头部注入 RFC 8785 Manifest SHA-256 摘要。
 */
export function generateActionTypes(manifest: ActionDockManifest): { code: string; digest: string } {
  const digest = computeManifestDigest(manifest);
  const actions = manifest.actions || {};
  const actionEntries = Object.entries(actions);

  const namespaceBlocks = actionEntries.map(([actionId, item]) => {
    const name = toPascalCase(actionId);
    const inType = jsonSchemaToTypeScript(item.inputSchema, 4);
    const outType = jsonSchemaToTypeScript(item.outputSchema, 4);
    const descComment = item.description
      ? `    /**\n     * ${item.description.replace(/\*\//g, "* /")}\n     */\n`
      : "";
    return `  export namespace ${name} {\n${descComment}    export type Input = ${inType};\n    export type Output = ${outType};\n  }`;
  });

  const mapEntries = actionEntries.map(([actionId]) => {
    const name = toPascalCase(actionId);
    return `    "${actionId}": {\n      Input: Actions.${name}.Input;\n      Output: Actions.${name}.Output;\n    };`;
  });

  const code = `/**
 * AUTO-GENERATED BY ACTIONDOCK. DO NOT EDIT DIRECTLY.
 * @manifest-digest ${digest}
 */

import type { ActionContext, ActionDefinition } from "@actiondock/sdk";

export namespace Actions {
${namespaceBlocks.join("\n\n")}
}

export interface ActionSchemaMap {
${mapEntries.join("\n")}
}

export type ActionInput<T extends keyof ActionSchemaMap> = ActionSchemaMap[T]["Input"];
export type ActionOutput<T extends keyof ActionSchemaMap> = ActionSchemaMap[T]["Output"];

export type TypedActionDefinition<T extends keyof ActionSchemaMap> = ActionDefinition<
  ActionSchemaMap[T]["Input"],
  ActionSchemaMap[T]["Output"]
>;
`;

  return { code, digest };
}

/**
 * 将生成的类型声明写入到项目的 .actiondock/generated/actions.d.ts 文件。
 */
export function writeActionTypes(
  projectRoot: string,
  manifest?: ActionDockManifest | null
): { filePath: string; digest: string } {
  const targetManifest = manifest || loadManifest(projectRoot);
  if (!targetManifest) {
    throw new Error(`actiondock.json not found in ${projectRoot}`);
  }
  const { code, digest } = generateActionTypes(targetManifest);
  const fullPath = join(projectRoot, GENERATED_TYPES_REL_PATH);
  const dir = dirname(fullPath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  writeFileSync(fullPath, code, "utf-8");
  return { filePath: fullPath, digest };
}

/**
 * 只读检查项目中的 .actiondock/generated/actions.d.ts 是否过期。
 * 若文件不存在，则认为无需校验通过（返回 exists: false, outdated: false）。
 * 若文件存在但摘要与当前 actiondock.json 不一致，则返回 outdated: true。
 */
export function checkGeneratedTypes(
  projectRoot: string,
  manifest?: ActionDockManifest | null
): {
  exists: boolean;
  outdated: boolean;
  expectedDigest?: string;
  actualDigest?: string;
  filePath: string;
} {
  const fullPath = join(projectRoot, GENERATED_TYPES_REL_PATH);
  if (!existsSync(fullPath)) {
    return { exists: false, outdated: false, filePath: fullPath };
  }

  const targetManifest = manifest || loadManifest(projectRoot);
  if (!targetManifest) {
    return { exists: true, outdated: true, filePath: fullPath };
  }

  const expectedDigest = computeManifestDigest(targetManifest);
  try {
    const content = readFileSync(fullPath, "utf-8");
    const match = content.match(/@manifest-digest\s+([^\s*]+)/);
    const actualDigest = match ? match[1] : undefined;
    const outdated = actualDigest !== expectedDigest;
    return {
      exists: true,
      outdated,
      expectedDigest,
      actualDigest,
      filePath: fullPath,
    };
  } catch {
    return {
      exists: true,
      outdated: true,
      expectedDigest,
      filePath: fullPath,
    };
  }
}
