package org.team4u.actiondock.domain.model;

public enum PlaybookTraceEventType {
    PLAYBOOK_CANDIDATES_LISTED,
    PLAYBOOK_SELECTED,
    PLAYBOOK_REJECTED,
    FALLBACK_SELECTED,

    BOUNDARY_READ,
    STOP_CONDITION_CHECKED,
    STOP_CONDITION_HIT,
    RISK_ACCEPTED,
    CONFIRMATION_REQUESTED,
    CONFIRMATION_GRANTED,
    CONFIRMATION_DENIED,

    AGENT_SKILL_HINT_CHECKED,
    AGENT_SKILL_AVAILABLE,
    AGENT_SKILL_UNAVAILABLE,

    GUIDE_READ,
    KNOWLEDGE_REF_SELECTED,
    KNOWLEDGE_REF_READ,
    SCRIPT_SCHEMA_QUERIED,
    SCRIPT_CANDIDATE_SELECTED,
    SCRIPT_CANDIDATE_SKIPPED,
    QUESTION_LIST_CREATED,
    CONTEXT_FIELD_RESOLVED,
    CONTEXT_FIELD_MISSING,

    SCRIPT_EXECUTION_REQUESTED,
    SCRIPT_EXECUTION_STARTED,
    SCRIPT_EXECUTION_FINISHED,
    SCRIPT_EXECUTION_FAILED,
    DIAGNOSIS_EMITTED,
    PLAYBOOK_HANDOFF_SUGGESTED,
    PLAYBOOK_HANDOFF_STARTED,

    SESSION_STARTED,
    SESSION_COMPLETED,
    SESSION_STOPPED,
    SESSION_FAILED
}
